### ISSUE TITLE
Matlab visualization examples

### ISSUE THREAD

**Issue by JeremyPike** [appliedtopology/javaplex#16]
Hi

Im trying to run the Matlab visualization examples, specifically witness_sphere_opengl.m. Im using Windows 7, Matlab R2017a and the latest javaplex release (4.3.1).  I get the following error message, I have tried to add jogl.jar to the Matlab java path but this dosnt help. Any advice would be much appreciated.

Thank you

Jeremy

-----------------------------

Error using render_onscreen (line 5)
Java exception occurred:
java.lang.UnsatisfiedLinkError: no jogl in java.library.path

	at java.lang.ClassLoader.loadLibrary(Unknown Source)

	at java.lang.Runtime.loadLibrary0(Unknown Source)

	at java.lang.System.loadLibrary(Unknown Source)

	at com.sun.opengl.impl.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:189)

	at com.sun.opengl.impl.NativeLibLoader.access$000(NativeLibLoader.java:49)

	at com.sun.opengl.impl.NativeLibLoader$DefaultAction.loadLibrary(NativeLibLoader.java:80)

	at com.sun.opengl.impl.NativeLibLoader.loadLibrary(NativeLibLoader.java:103)

	at com.sun.opengl.impl.NativeLibLoader.access$200(NativeLibLoader.java:49)

	at com.sun.opengl.impl.NativeLibLoader$1.run(NativeLibLoader.java:111)

	at java.security.AccessController.doPrivileged(Native Method)

	at com.sun.opengl.impl.NativeLibLoader.loadCore(NativeLibLoader.java:109)

	at com.sun.opengl.impl.windows.WindowsGLDrawableFactory.<clinit>(WindowsGLDrawableFactory.java:60)

	at java.lang.Class.forName0(Native Method)

	at java.lang.Class.forName(Unknown Source)

	at javax.media.opengl.GLDrawableFactory.getFactory(GLDrawableFactory.java:106)

	at javax.media.opengl.GLCanvas.chooseGraphicsConfiguration(GLCanvas.java:520)

	at javax.media.opengl.GLCanvas.<init>(GLCanvas.java:131)

	at javax.media.opengl.GLCanvas.<init>(GLCanvas.java:90)

	at javax.media.opengl.GLCanvas.<init>(GLCanvas.java:83)

	at edu.stanford.math.plex_viewer.gl.OpenGLManager.<init>(Unknown Source)

	at edu.stanford.math.plex_viewer.Api.drawSimplexStream(Unknown Source)

Error in witness_sphere_opengl (line 32)
render_onscreen(stream, point_cloud);

**Comment by henryadams** [comment]
Hi Jeremy,

I've never myself tried to use the Matlab visualization examples, so I don't have much advice to give. I'm assuming you were able to get the routines in the Javaplex tutorial working? If so, then I don't have much more expertise than that. Perhaps @michiexile  or @ogdet know a bit more here.

Best, Henry

**Comment by JeremyPike** [comment]
Hi

Thanks for the response.  Yes the routines in the Javaplex tutorial work well.

Best
Jeremy
