### ISSUE TITLE
Bottleneck Distance on large arrays

### ISSUE THREAD

**Issue by carshadi** [appliedtopology/javaplex#26]
Hello,

I am trying to compute the bottleneck distances (using the java code) between two persistence diagrams, where a diagram is 2D double array resembling (truncated since they contain hundreds to thousands of "intervals"):
```[0.0, 176.507168786259], [0.0, 156.45306562335224], [0.0, 189.94726493710797], [0.0, 195.10214298400348], [0.0, 143.8279528458195], [0.0, 156.20164106459742], [0.0, 179.03489557186467], [0.0, 796.7827854139772], [0.0, 17042.99673233599], [0.0, 131.86219199823918], [0.0, 227.1776163350727], [0.0, 1215.6844252316769], [12.048679885714341, 115.31355092648784], [15.599417052357564, 143.08484386531893], ... ]```

I am not sure if this is the correct format for the data but when comparing two large diagrams (hundreds of points) I get an IndexOutOfBounds exception
```at edu.stanford.math.plex4.bottleneck.FordFulkerson.stpath(FordFulkerson.java:158)
	at edu.stanford.math.plex4.bottleneck.FordFulkerson.solve(FordFulkerson.java:56)
	at edu.stanford.math.plex4.bottleneck.FordFulkerson.maxFlow(FordFulkerson.java:42)
	at edu.stanford.math.plex4.bottleneck.WeightedBipartiteGraph.computeMaximumCardinalityMatching(WeightedBipartiteGraph.java:130)
	at edu.stanford.math.plex4.bottleneck.WeightedBipartiteGraph.hasPerfectMatching(WeightedBipartiteGraph.java:136)
	at edu.stanford.math.plex4.bottleneck.WeightedBipartiteGraph.computePerfectMatchingThreshold(WeightedBipartiteGraph.java:151)
	at edu.stanford.math.plex4.bottleneck.BottleneckDistance.computeBottleneckDistance(BottleneckDistance.java:116)
	at edu.stanford.math.plex4.bottleneck.BottleneckDistance.computeBottleneckDistance(BottleneckDistance.java:79)
	at sc.fiji.snt.analysis.PersistenceAnalyzer.getBottleneckDistance(PersistenceAnalyzer.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
java.lang.ArrayIndexOutOfBoundsException: java.lang.ArrayIndexOutOfBoundsException: 1000
```

It appears to work for smaller sets of points, I was wondering if there is anything special I have to do when dealing with larger point sets (and if the format im using is even correct)

Thank you!

**Comment by michiexile** [comment]
The JavaPlex bottleneck distance implementation has a known problem where the size of persistence diagrams is limited to 1000 bars.

We are looking into improving this piece of code, but have not yet finished.
--
Mikael Vejdemo-Johansson
mikael@johanssons.org

**Comment by carshadi** [comment]
I see, thanks for the quick reply!
