### ISSUE TITLE
How to use plex-viewer

### ISSUE THREAD

**Issue by tmelorc** [appliedtopology/javaplex#9]
I'm starting to learn `javaplex` and I found [here](https://github.com/appliedtopology/javaplex/wiki/Overview) a link to `plex-viewer` [here](http://code.google.com/p/plex-viewer/).

I tried some example with

> `./run_x86.sh -complex rips_simplices.txt -points rips_points.txt`

from the README file. But I got the errors below.

Do you have some idea how to fix or maybe some other software to
create simplicial complexes from data created by `javaplex`?

Regards and thanks in advance.

Thiago de Melo
www.rc.unesp.br/tmelo

```
Exception in thread "main" java.lang.NoClassDefFoundError:
edu/stanford/math/plex4/io/SimplexStreamReaderWriter
        at edu.stanford.math.plex_viewer.SimplexStreamViewer.renderFromFiles(Unknown
Source)
        at edu.stanford.math.plex_viewer.SimplexStreamViewer.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException:
edu.stanford.math.plex4.io.SimplexStreamReaderWriter
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 2 more
```

**Comment by michiexile** [comment]
Ping @henryadams , @ogdet -- I'm not really familiar with plex_viewer myself.

**Comment by henryadams** [comment]
I've never used plex_viewer either, but as you say maybe @ogdet has comments.

Best, Henry

**Comment by petercrlane** [comment]
I got the two README examples of plex-viewer to work by adding the javaplex jar file to CPATH in the .sh scripts.

e.g. copy javaplex-4.2.5.jar to 'examples', and change CPATH in the .sh scripts to:
CPATH="plex-viewer.jar:../lib/ext/gluegen-rt.jar:../lib/ext/jogl.jar:javaplex-4.2.5.jar"

I downloaded the files (which include the opengl lib files) from: https://github.com/ogdet/plex-viewer
